apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  env: dev
images:
  - name: nginx
    newName: nginx
    newTag: 1.0.0
resources:
  - ./../../base # baseへのパス
