apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
  env: prod
images:
  - name: nginx
    newName: nginx
    newTag: 1.0.0
resources:
  - ./../../base
patchesStrategicMerge:
  - deployment.yaml
